apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-service
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
      - name: java-service
        image: us-central1-docker.pkg.dev/k8s-polyglot-test-1/java-service/java-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
