apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pull-image-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pull-image-role
  apiGroup: rbac.authorization.k8s.io
